version: "1"

ai:
  provider: cerebras
  model: gpt-oss-120b
  api_key_env: CEREBRAS_API_KEY
  max_tokens: 8000
  temperature: 0.3
  timeout: 30s

  retry:
    attempts: 3
    backoff: exponential
    initial_delay: 2s

  polish:
    enabled: true
    polish_model: "google/gemini-2.5-flash"
    polish_provider: "openrouter"
    polish_api_key_env: "OPENROUTER_API_KEY"
    polish_max_tokens: 4000
    polish_temperature: 0.3

output:
  format: keepachangelog
  sections:
    - breaking
    - added
    - changed
    - fixed
    - docs

filters:
  files:
    include:
      - "*.go"
      - "*.md"
      - "*.yml"
      - "*.yaml"
      - "*.json"
    exclude:
      - "CHANGELOG.md"
      - "README.md"
      - ".promptext-notes.example.yml"
      - "*_test.go"
      - "vendor/*"
      - "node_modules/*"
      - ".git/*"
  commits:
    exclude_authors:
      - "dependabot[bot]"
      - "renovate[bot]"
      - "github-actions[bot]"
    exclude_patterns:
      - "^Merge pull request"
      - "^Merge branch"
