# Promptext-Notes Configuration
# Optimized for production releases with 2-stage polish workflow

version: "1"

ai:
  provider: cerebras
  model: zai-glm-4.6  # Best free model (10/10 accuracy)
  api_key_env: CEREBRAS_API_KEY
  max_tokens: 8000
  temperature: 0.3
  timeout: 30s

  retry:
    attempts: 3
    backoff: exponential
    initial_delay: 2s

  custom: {}

  # 2-Stage Polish Workflow
  # Stage 1 (Discovery): Uses ai.model (zai-glm-4.6 on Cerebras above - FREE)
  # Stage 2 (Polish): Uses polish_model on OpenRouter below
  polish:
    enabled: false  # Enable via --polish flag or set to true
    polish_model: "anthropic/claude-sonnet-4.5"  # Best polish model (8/10 accuracy)
    polish_provider: "openrouter"
    polish_api_key_env: "OPENROUTER_API_KEY"
    polish_max_tokens: 4000
    polish_temperature: 0.3

output:
  format: keepachangelog
  sections:
    - breaking
    - added
    - changed
    - fixed
    - docs

filters:
  files:
    include:
      - "*.go"
      - "*.md"
      - "*.yml"
      - "*.yaml"
      - "*.json"
    exclude:
      - "CHANGELOG.md"
      - "README.md"
      - ".promptext-notes.example.yml"
      - "*_test.go"
      - "vendor/*"
      - "node_modules/*"
      - ".git/*"
  commits:
    exclude_authors:
      - "dependabot[bot]"
      - "renovate[bot]"
      - "github-actions[bot]"
    exclude_patterns:
      - "^Merge pull request"
      - "^Merge branch"
